from .config import Settings
from .logs import Corpus

BADGE = {"supported": "verified", "partial": "partially verified", "unsupported": "NOT verified"}


def _claim(item: dict, verdicts: dict, corpus_refs: set) -> str:
    refs = ", ".join(f"`{r}`" for r in item.get("refs", []) if r in corpus_refs) or "no citation"
    verdict = verdicts.get(item.get("id", ""), {}).get("verdict")
    badge = f" _({BADGE[verdict]})_" if verdict in BADGE else ""
    return f"{item.get('statement', '').strip()} [{refs}]{badge}"


def to_markdown(analysis: dict, verdicts: dict, corpus: Corpus, usage: dict, settings: Settings) -> str:
    refs = {line.ref for line in corpus.lines}
    out: list[str] = []
    out.append(f"# Postmortem: {analysis.get('title', 'Incident')}")
    window = analysis.get("window") or {}
    out.append(f"**Severity:** {analysis.get('severity', 'n/a')}  ")
    out.append(f"**Window:** {window.get('start', '?')} to {window.get('end', '?')}  ")
    out.append("**Format:** blameless; every claim cites log lines and was re-checked by an independent verifier model.\n")
    out.append("## Summary\n")
    out.append(str(analysis.get("summary", "")).strip() + "\n")
    for key, heading in (("impact", "Impact"), ("trigger", "Trigger"), ("root_cause", "Root cause"), ("detection", "Detection"), ("resolution", "Resolution")):
        item = analysis.get(key)
        if isinstance(item, dict) and item.get("statement"):
            out.append(f"## {heading}\n\n{_claim(item, verdicts, refs)}\n")
    for key, heading in (("causal_chain", "Causal chain"), ("contributing_factors", "Contributing factors"), ("red_herrings", "Ruled out (red herrings)")):
        items = analysis.get(key) or []
        if items:
            out.append(f"## {heading}\n")
            marker = "1." if key == "causal_chain" else "-"
            out.extend(f"{marker} {_claim(item, verdicts, refs)}" for item in items)
            out.append("")
    actions = analysis.get("action_items") or []
    if actions:
        out.append("## Action items\n")
        out.append("| Priority | Type | Action |")
        out.append("|---|---|---|")
        out.extend(f"| {a.get('priority', '')} | {a.get('type', '')} | {str(a.get('action', '')).replace('|', '/')} |" for a in actions if isinstance(a, dict))
        out.append("")
    questions = analysis.get("open_questions") or []
    if questions:
        out.append("## Open questions\n")
        out.extend(f"- {q}" for q in questions)
        out.append("")
    cited = sorted({r for item in _all_claims(analysis) for r in item.get("refs", []) if r in refs}, key=_ref_key)
    if cited:
        by_ref = corpus.by_ref()
        names = {s["id"]: s["name"] for s in corpus.sources}
        out.append("## Evidence\n")
        out.append("```")
        out.extend(f"[{r}] ({names.get(r.split(':')[0], '')}) {by_ref[r].text}" for r in cited)
        out.append("```\n")
    out.append("---")
    out.append(f"Generated by Postmortem Pilot on Nebius Token Factory: events extracted by `{settings.extract_model}`, causal analysis by `{settings.reason_model}`, claims verified by `{settings.verify_model}`. Total tokens: {usage.get('total_tokens', 0)}.")
    return "\n".join(out)


def _all_claims(analysis: dict):
    for key in ("impact", "trigger", "root_cause", "detection", "resolution"):
        if isinstance(analysis.get(key), dict):
            yield analysis[key]
    for key in ("causal_chain", "contributing_factors", "red_herrings"):
        yield from (i for i in analysis.get(key) or [] if isinstance(i, dict))


def _ref_key(ref: str):
    source, _, line = ref.partition(":")
    return (int(source[1:] or 0), int(line or 0))
